compat and blacklists
EccentricVamp/EccentricTome pull request #22
Opened 2022-07-28 02:16 UTC by NyanMC

adds compat for enigmatic legacy's guide book "the acknowledgment", and blacklists some items which are used (and consumed) in crafting
the added blacklisted items are as follows:
dark utils: galactic, runelic, and restoration tomes (or "books" going by their resource name) (these items are applied via smithing table and are consumed on use, and the internal names are presumably the 1.16 equivalent to the tomes)
projecte: tome of knowledge (this item is only needed once, and you can easily void your entire tome on accident with it)
quark: ancient tomes (same as the dark utils items, but these are applied via crafting table, they're still consumed on use though)
the vanilla minecraft enchanted book is on here as despite the mod having a built-in blacklist for minecraft it does not prevent enchants from other mods from going into the book

2022-07-28 23:43 UTC, EccentricVamp requested changes

2022-07-28 23:43 UTC, EccentricVamp commented on src/main/java/website/eccentric/tome/CommonConfiguration.java
> +                    "darkutils:book_restore",
```suggestion
```

These got renamed to "tomes" in 1.18. I've opened a separate pull request for [1.16.5 fixes](https://github.com/EccentricVamp/EccentricTome/pull/23). I'll be making the changes there and doing some clean up.

2022-07-28 23:43 UTC, EccentricVamp commented on src/main/java/website/eccentric/tome/CommonConfiguration.java
> +                    "minecraft:enchanted_book",
```suggestion
```

I'd only intended the Eccentric Tome to hold guidebooks. But you make a good point about third-party enchanted books and other books in general. Since I don't have a good way to filter those out, might as well embrace them. However, this would be a big change so I'd like more time to think about it.

Please remove this line for now. I've opened up [an issue](https://github.com/EccentricVamp/EccentricTome/issues/24) so that I don't forget about it.

2022-07-29 00:31 UTC, EccentricVamp commented
\*Facepalm\*

I just realized I butchered this pull request. I though this was a pull request for main.

You did the right thing and opened this pull request on the 1.16.5 branch but I wasn't paying attention, sorry! If it's okay with you, I'll go ahead and close this one since the changes have been made in https://github.com/EccentricVamp/EccentricTome/pull/23.

Thanks for opening up a pull request! I hope I didn't scare you away with my shenanigans.

2022-07-29 02:00 UTC, NyanMC commented
> Since I don't have a good way to filter those out, might as well embrace them.

...but you do have a way, that's why i added minecraft:enchanted_book to the _blacklist_. that causes all mod enchantments to be filtered out, as they are all registered under the vanilla item unless they handle the enchantment in a weird way.
i can still remove the line if you want, i just wanted to clarify that first.

2022-07-29 23:52 UTC, merged

2022-07-29 23:52 UTC, EccentricVamp commented
> they are all registered under the vanilla item

I didn't realize that. Good to know

> i can still remove the line if you want

No need. I might investigate enchanted books more in the future, but in the meantime lets get this merged.

I think I'll push this out sometime this weekend as Eccentric Tome 1.8-beta.